quarkus.http.port=8585
# Session manager
quarkus.rest-client.session-manager.url=http://localhost:8181
# Liquibase minimal config properties
quarkus.liquibase.migrate-at-start=true
# Liquibase optional config properties
quarkus.liquibase.enabled=true
quarkus.liquibase.change-log=liquibase/db/changeLog.xml
quarkus.liquibase.clean-at-start=true

